name: Manually Tag Commit

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Auto tag
      run: |
        git fetch --all --tags
        latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
        new_tag="v$(echo $latest_tag | awk -F. '{printf "%d.%d", $1, $2+1}')"
        
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git tag $new_tag
        git push origin $new_tag

